name: postgres16

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name : install psql
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client


      - name: Run the global tests
        run: psql -f locks.sql
        env:
          DBURL: postgres://postgres:postgres@localhost:5432/postgres
