name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgresql-version: [14, 15, 16]
    steps:
    - name: Install PostgreSQL
      env:
        POSTGRESQL_VERSION: ${{ matrix.postgresql-version }}
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y install "postgresql-$POSTGRESQL_VERSION"
    - name: Run tests
      env:
        POSTGRESQL_VERSION: ${{ matrix.postgresql-version }}
      run: |
        export POSTGRESQL_PATH="/usr/lib/postgresql/$POSTGRESQL_VERSION/bin/postgres"
        export INITDB_PATH="/usr/lib/postgresql/$POSTGRESQL_VERSION/bin/initdb"
        pytest
